### ISSUE TITLE
The low results

### ISSUE THREAD

**Issue by JerryZeyu** [THUDM/CogQA#8]
The final results are very low: {'em': 0.03551654287643484, 'f1': 0.0478604024080054, 'prec': 0.051990450467830615, 'recall': 0.0491018037405613, 'sp_em': 0.0005401755570560432, 'sp_f1': 0.12093599476326915, 'sp_prec': 0.07244085040682292, 'sp_recall': 0.42420838558245866, 'joint_em': 0.0001350438892640108, 'joint_f1': 0.009409090423642906, 'joint_prec': 0.005848759671643607, 'joint_recall': 0.03384786494172044} which is nearly 10 times worse than your results in the paper. Can you tell me the reason?

**Comment by qibinc** [comment]
Hi @JerryZeyu ,

We're interested in why your reproduction fails. Please provide more details of your training and evaluation. Make sure that you followed every steps in README.

Thanks!

**Comment by Sleepychord** [comment]
Hi, @JerryZeyu . I have reply your email and did not get response.  As I said, I guess that you did not training successfully, because I find that you're training on 1 GPU and its memory usually is not enough for batch_size > 2(default 12). Maybe you need at least 5 GPU for that task#2 must be trained as a whole graph. And you should also check the redis database. I have double checked the reproducibility and can guarantee it. I am also interesting in your failure and contact me if you find the reason.

**Comment by JerryZeyu** [comment]
Hi, I am very glad to receive your reply. Because I just have 1 GPU. And
the memory on my GPU is only enough for batch=2.  So can you tell me
whether the batch=2 will result in training failure? I am very looking
forward to receive your reply. Thank you very much.

Best Regards,
Zeyu Zhang

**Comment by JerryZeyu** [comment]
Hi am very glad to receive your reply. Because I just have 1 GPU. And the
memory on my GPU is only enough for batch=2.  So can you tell me whether
the batch=2 will result in training failure? I am very looking forward to
receive your reply. Thank you very much.

Best Regards,
Zeyu Zhang

**Comment by Sleepychord** [comment]
Hi, @JerryZeyu . I am afraid that you need at least 5 GPU for that task#2 must be trained as a whole graph. But you can just only train task #1 using batch_size=2.

**Comment by PeterAJansen** [comment]
Hi @Sleepychord, would you happen to have a list of detailed requirements for running this code?  (I did not see these in the README).  Can I ask what kind of hardware you're running it on?  (e.g. a local HPC, or a cloud computing system that has access to a single machine with 5 GPUs that we might try to use to replicate it?).  Thanks.

**Comment by PeterAJansen** [comment]
Also, does the code throw any error messages/stop running/etc when it can't access enough resources to run, or is the only way to know if it ran successfully to run the evaluation script and replicate the results?

**Comment by PeterAJansen** [comment]
As a follow-up, after going through the code (with my limited understanding of Pytorch) -- it looks like this code is architected such that it needs a single machine with many GPUs (it sounds like at least 5?), rather than (for example) an HPC with many single-GPU nodes that can be bridged using the Distributed capabilities of Pytorch (e.g. https://pytorch.org/tutorials/intermediate/dist_tuto.html ).  Does that sound correct?

**Comment by qibinc** [comment]
Hi @PeterAJansen ,

For now we can only guarantee performance on a single machine with many GPUs (we trained and tested on 8 V100s).

Training on many single-GPU nodes needs communication **across processes**. To achieve this in PyTorch, you need to change every occurrence of `DataParallel` to `DistributedDataParallel`. Unfortunately, we don't have the condition to test this. If you obtain any good or bad results when trying with `DistributedDataParallel`, please kindly let us know.

Thanks!

**Comment by PeterAJansen** [comment]
Hi @qibinc,
Thanks for these more detailed specifications.  I would highly recommend the following: 

1) Post these detailed specifications in your README, so that it's clear what the minimum requirements for training/evaluating/running this code are. 
2) Modify the code to do some coarse check for these minimum requirements (e.g. checking that there are a minimum of 5 GPUs with >11GB of memory for a batch size of 10), and exit with a failure message if these minimum requirements are not met. 

Right now there are no requirements posted (and the requirements you've mentioned require a specialized machine), and the code appears to allow the user to run through the entire evaluation procedure even if it was unsuccessful.  This makes the results very challenging to replicate. 

best wishes,
Peter

**Comment by Sleepychord** [comment]
Hi, @PeterAJansen . Thank you for you suggestion. We will test the specification as soon as possible, but in advance I just wonder why "the code appears to allow the user to run through the entire evaluation procedure even if it was unsuccessful". Have you encounter the same problem? In my impression, if you run it on only one GPU, you will get the OutOfMemory Error in Pytorch. It will not run through the entire training procedure. If so, I am really want to know the details. Thank you very much.

**Comment by JerryZeyu** [comment]
Hi,

If I reduce the batch_size to 2, I can use only one GPU to train and I
don't know the batch_size=2 will result in that it couldn't get a whole
graph. This is why the code appears to allow the user to run through the
entire evaluation procedure even if it was unsuccessful. Thanks.

Best Regards,
Zeyu Zhang
